### ISSUE TITLE
feat: melosからPub Workspacesへの移行

### ISSUE THREAD

**Issue by salan70** [salan70/baseball_player_journey#33]
### 概要
現在のプロジェクトはmelosを使用したマルチパッケージ構成になっていますが、Dart 3.0から導入されたPub Workspacesを使用した構成に移行したいと考えています。これにより、依存関係の管理がシンプルになり、ビルド時間の短縮やメンテナンス性の向上が期待できます。

### 背景と目的
- melosは優れたツールですが、Dart 3.0からネイティブでサポートされるようになったPub Workspacesを使用することで、追加のツール依存を減らすことができます
- Pub Workspacesを使用することで、より標準的なDart/Flutterのエコシステムに沿った開発が可能になります
- 将来的なDart/Flutterのアップデートに対する互換性が向上します
- ビルドプロセスの簡素化
- 依存関係管理の改善
- プロジェクト構成のモダン化

### 実装内容
1. ルートのpubspec.yamlにworkspaceの設定を追加
   ```yaml
   name: baseball_player_journey
   publish_to: none

   workspaces:
     - packages/**
   ```

2. 各パッケージのpubspec.yamlを更新して相対パスでの依存関係を設定
   ```yaml
   dependencies:
     domain:
       path: ../domain
   ```

3. melosで実行していたスクリプトをMakefileに移行
   - clean
   - test
   - analyze
   - format
   - gen (build_runner)

4. CI/CDパイプラインの更新（必要に応じて）

5. ドキュメントの更新
   - READMEの更新
   - 開発環境セットアップ手順の更新

6. 移行後のテスト実行
   - 各パッケージのビルド確認
   - テストの実行確認
   - 依存関係の解決確認

### 技術的考慮事項
- Pub Workspacesは比較的新しい機能であるため、互換性の問題が発生する可能性があります
- 現在melosで実行しているスクリプトの代替手段を検討する必要があります
- 依存関係の解決方法が変わるため、ビルドやテストのプロセスに影響がある可能性があります
- Flutterのバージョン管理（FVM）との連携方法を検討する必要があります

### 参考リンク
- [Pub Workspaces Documentation](https://dart.dev/guides/libraries/workspaces)
- [Flutter Workspaces Example](https://github.com/flutter/samples/tree/main/add_to_app/multiple_flutters/multiple_flutters_module)
- [Migrating from Melos to Pub Workspaces](https://pub.dev/packages/melos#migrating-from-melos-to-pub-workspaces)

### 見積時間
総見積時間: 8時間
- 調査と計画: 2時間
- 実装: 4時間
- テストと検証: 2時間
